(function journalSyncEngineFactory(root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.LifelineJournalSync = api;
}(typeof globalThis !== 'undefined' ? globalThis : this, () => {
  const ACTIONS = Object.freeze({ IDENTICAL:'identical', IMPORT:'import_remote', CREATE:'create_remote', UPDATE_LOCAL:'update_local', UPDATE_REMOTE:'update_remote', DELETE_LOCAL:'delete_local', DELETE_REMOTE:'delete_remote', CLOSED:'close_deletion', CONFLICT:'conflict', UNCERTAIN:'uncertain_match' });
  function cleanDescription(value) { return String(value || '').replace(/\r\n?/g, '\n').split('\n').map((line) => line.trim().replace(/[ \t]+/g, ' ')).join('\n').trim(); }
  function cleanKeywords(value) {
    const source = Array.isArray(value) ? value : String(value || '').split(/[\n,]+/); const seen = new Set(); const display=[];
    for (const item of source) { const word=String(item||'').trim().replace(/\s+/g,' '); const key=word.toLocaleLowerCase(); if (!word || seen.has(key)) continue; if (word.length > 50) throw new Error('KEYWORD EXCEEDS 50 CHARACTERS'); seen.add(key); display.push(word); }
    if (display.length > 8) throw new Error('KEYWORD LIMIT EXCEEDED'); return display;
  }
  function normalizeJournal(record={}, scope='personal') { const keywords=cleanKeywords(record.keywords ?? record.keyphrases ?? record.journal_keywords ?? record.word); const description=cleanDescription(record.description ?? record.entry ?? record.journal_description ?? ''); if (description.length>500) throw new Error('DESCRIPTION EXCEEDS 500 CHARACTERS'); return { scope, keywords, normalized_keywords:keywords.map(x=>x.toLocaleLowerCase()).sort(), description, deleted:Boolean(record.deleted_at) }; }
  function hashString(text) { let h1=0xdeadbeef^text.length,h2=0x41c6ce57^text.length; for(let i=0,ch;i<text.length;i++){ch=text.charCodeAt(i);h1=Math.imul(h1^ch,2654435761);h2=Math.imul(h2^ch,1597334677);} h1=Math.imul(h1^(h1>>>16),2246822507)^Math.imul(h2^(h2>>>13),3266489909);h2=Math.imul(h2^(h2>>>16),2246822507)^Math.imul(h1^(h1>>>13),3266489909);return (4294967296*(2097151&h2)+(h1>>>0)).toString(16).padStart(14,'0'); }
  function hashJournal(record,scope='personal') { const n=normalizeJournal(record,scope); return hashString(JSON.stringify([n.scope,n.normalized_keywords,n.description])); }
  function baselineOf(local) { const sync=local?.kindroid_sync||{}; if(!sync.baseline_hash)return null; return {hash:sync.baseline_hash,keywords:sync.baseline_keywords||[],description:sync.baseline_description||''}; }
  function matchEntries(locals=[],remotes=[],scope='personal') {
    const available=new Set(remotes.map((_,i)=>i)); const matches=[]; const ambiguous=[];
    for(const local of locals){ let candidates=[]; const rid=String(local?.kindroid_sync?.remote_id||''); if(rid)candidates=[...available].filter(i=>String(remotes[i].remote_id||'')===rid); const baseline=baselineOf(local);if(!candidates.length&&baseline)candidates=[...available].filter(i=>hashJournal(remotes[i],scope)===baseline.hash); if(!candidates.length){const lh=hashJournal(local,scope);candidates=[...available].filter(i=>hashJournal(remotes[i],scope)===lh);} if(!candidates.length){const p=normalizeJournal(local,scope).normalized_keywords[0];candidates=[...available].filter(i=>{const rn=normalizeJournal(remotes[i],scope);return p&&rn.normalized_keywords[0]===p&&hashString(rn.description)===hashString(normalizeJournal(local,scope).description);});} if(candidates.length===1){available.delete(candidates[0]);matches.push({local,remote:remotes[candidates[0]]});}else if(candidates.length>1)ambiguous.push({local,remotes:candidates.map(i=>remotes[i])});else matches.push({local,remote:null}); }
    return {matches,remoteOnly:[...available].map(i=>remotes[i]),ambiguous};
  }
  function decide(local,remote,scope,initialized){ const base=baselineOf(local); const ld=Boolean(local?.deleted_at); if(!initialized||!base){if(ld)return ACTIONS.IDENTICAL;if(!remote)return ACTIONS.CREATE;return hashJournal(local,scope)===hashJournal(remote,scope)?ACTIONS.IDENTICAL:ACTIONS.CONFLICT;} const lh=ld?null:hashJournal(local,scope),rh=remote?hashJournal(remote,scope):null,bh=base.hash; if(!lh&&!rh)return ACTIONS.CLOSED;if(!lh)return rh===bh?ACTIONS.DELETE_REMOTE:ACTIONS.CONFLICT;if(!rh)return lh===bh?ACTIONS.DELETE_LOCAL:ACTIONS.CONFLICT;if(lh===rh)return ACTIONS.IDENTICAL;if(lh===bh)return ACTIONS.UPDATE_LOCAL;if(rh===bh)return ACTIONS.UPDATE_REMOTE;return ACTIONS.CONFLICT; }
  function buildSynchronizationPlan({locals=[],remotes=[],scope='personal',initialized=false}={}) { const matched=matchEntries(locals,remotes,scope); const operations=[]; for(const pair of matched.matches)operations.push({...pair,action:decide(pair.local,pair.remote,scope,initialized)}); for(const remote of matched.remoteOnly)operations.push({local:null,remote,action:ACTIONS.IMPORT}); for(const item of matched.ambiguous)operations.push({...item,remote:null,action:ACTIONS.UNCERTAIN}); const counts={}; Object.values(ACTIONS).forEach(a=>counts[a]=0); operations.forEach(o=>counts[o.action]++); return {scope,initialized,operations,counts,hasBlocking:operations.some(o=>[ACTIONS.CONFLICT,ACTIONS.UNCERTAIN].includes(o.action))}; }
  function resolveConflict(operation,resolution){if(!['local','remote','exclude'].includes(resolution))throw new Error('A conflict resolution is required.');return {...operation,resolution,action:resolution==='local'?(operation.local?ACTIONS.UPDATE_REMOTE:ACTIONS.DELETE_REMOTE):resolution==='remote'?(operation.remote?ACTIONS.UPDATE_LOCAL:ACTIONS.DELETE_LOCAL):ACTIONS.IDENTICAL};}
  return {ACTIONS,normalizeJournal,hashJournal,matchEntries,buildSynchronizationPlan,resolveConflict};
}));
