'use strict';

const UI_MAP_ERROR = 'KINDROID JOURNAL UI MAP NEEDS UPDATE';
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

class KindroidJournalAdapter {
  constructor(window) { this.window = window; }
  async debug(stage,data={}) { const payload={stage,url:this.window?.webContents?.getURL?.()||'',at:new Date().toISOString(),...data};console.log('[JournalSyncAdapter]',payload);await this.run(`() => { console.log('[LIFELINE Journal Sync]', ${JSON.stringify(payload)}); return true; }`).catch(()=>false);return payload; }
  async debugDom(stage) { const snapshot=await this.run(`() => ({readyState:document.readyState,title:document.title,bodyText:String(document.body?.innerText||'').slice(0,1000),buttons:[...document.querySelectorAll('button')].map((button,index)=>({index,text:String(button.innerText||button.textContent||'').replace(/\\s+/g,' ').trim().slice(0,200),role:button.getAttribute('role'),ariaLabel:button.getAttribute('aria-label'),ariaChecked:button.getAttribute('aria-checked'),className:String(button.className||'').slice(0,200)})).slice(0,100),textareas:[...document.querySelectorAll('textarea')].map(x=>({placeholder:x.placeholder,maxLength:x.maxLength})),inputs:[...document.querySelectorAll('input')].map(x=>({placeholder:x.placeholder,type:x.type})).slice(0,50)}))`).catch(error=>({snapshotError:error.message}));return this.debug(stage,{dom:snapshot});}
  async run(source) { if (!this.window || this.window.isDestroyed()) throw new Error('Journal window is unavailable.'); return this.window.webContents.executeJavaScript(`(${source})()`); }
  async pageIsUsable(aiId='') { try { const url=new URL(this.window.webContents.getURL());if(!/(^|\.)kindroid\.ai$/i.test(url.hostname)||!url.pathname.includes(`/kin-settings/${encodeURIComponent(aiId)}`))return false;return await this.run(`() => document.readyState !== 'loading' && Boolean(document.body)`); } catch (_error) { return false; } }
  async openJournalPage(aiId) {
    const id=String(aiId||'').trim();if(!/^[A-Za-z0-9_-]{6,128}$/.test(id))throw new Error('NO VALID DIRECTORY AI ID');
    const target=`https://kindroid.ai/v2/kin-settings/${encodeURIComponent(id)}/?tab=journal`;
    // This is an isolated automation window, so navigate directly to the same
    // URL that worked before journal automation was separated from the panel.
    // A rejected promise is tolerated only when the expected page still renders.
    await this.debug('navigation:start',{target});let navigationError=null;try{await this.window.loadURL(target);await this.debug('navigation:loadURL-resolved');}catch(error){navigationError=error;await this.debug('navigation:loadURL-rejected',{error:error.message});}
    for(let attempt=0;attempt<60;attempt++){await sleep(250);const url=this.window.webContents.getURL();if(attempt%8===0)await this.debug('navigation:waiting',{attempt,url});if(/login|signin|auth/i.test(url))throw new Error('LOGIN REQUIRED');if(await this.pageIsUsable(id)){await sleep(1200);await this.debugDom('navigation:ready');return;}}
    if(navigationError)throw new Error(`JOURNAL PAGE FAILED TO LOAD: ${navigationError.message}`);
    throw new Error('JOURNAL PAGE FAILED TO LOAD');
  }
  async selectJournalScope(scope) { const wanted=scope==='global'?'Global':'Personal';await this.debugDom('scope:before-selection');let clicked=false;for(let attempt=0;attempt<40;attempt++){clicked=await this.run(`() => { const norm=s=>String(s||'').replace(/\\s+/g,' ').trim(); const button=[...document.querySelectorAll('button[role="radio"]')].find(x=>norm(x.textContent)===${JSON.stringify(wanted)}); if(!button)return false;if(button.getAttribute('aria-checked')!=='true')button.click();return true; }`);if(clicked){await this.debug('scope:clicked',{wanted,attempt});break;}if(attempt%8===0)await this.debug('scope:not-found',{wanted,attempt});await sleep(250);}if(!clicked){await this.debugDom('scope:failed-not-found');throw new Error(scope==='global'?'GLOBAL SCOPE COULD NOT BE SELECTED':UI_MAP_ERROR);}for(let attempt=0;attempt<20;attempt++){const selected=await this.run(`() => [...document.querySelectorAll('button[role="radio"]')].some(x=>String(x.textContent||'').replace(/\\s+/g,' ').trim()===${JSON.stringify(wanted)}&&x.getAttribute('aria-checked')==='true')`);if(selected){await this.debug('scope:confirmed',{wanted,attempt});return;}await sleep(200);}await this.debugDom('scope:failed-confirmation');throw new Error(scope==='global'?'GLOBAL SCOPE COULD NOT BE SELECTED':UI_MAP_ERROR); }
  async waitForJournalList() { for(let i=0;i<40;i++){const ok=await this.run(`() => {const n=s=>String(s||'').replace(/\\s+/g,' ').trim();const buttons=[...document.querySelectorAll('button')];const add=buttons.some(b=>/add|new|create/i.test(b.getAttribute('aria-label')||''));const row=buttons.some(b=>b.getAttribute('role')!=='radio'&&!b.getAttribute('aria-label')&&!b.closest('nav,header,[role="dialog"]')&&b.querySelectorAll('p,div,span').length>=2&&n(b.innerText));const empty=/no journal|no entr(?:y|ies)|empty/i.test(document.body.innerText);return add||row||empty;}`);if(ok)return;await sleep(250);}throw new Error('JOURNAL PAGE FAILED TO LOAD'); }
  async scanJournalIndex() {
    const rows=await this.run(`async () => {
      const norm=s=>String(s||'').replace(/\\s+/g,' ').trim();
      const ignored=/^(global|personal|save changes|delete entry|delete|back|add|new|create)$/i;
      const scrollables=()=>[document.scrollingElement,...document.querySelectorAll('main,section,div')].filter((x,i,a)=>x&&a.indexOf(x)===i&&x.scrollHeight>x.clientHeight+20);
      const container=scrollables().sort((a,b)=>(b.scrollHeight-b.clientHeight)-(a.scrollHeight-a.clientHeight))[0]||document.scrollingElement;
      const found=new Map(); let stable=0,last=-1;
      while(stable<5){
        [...document.querySelectorAll('button')].filter(button=>{
          const text=norm(button.innerText); const label=norm(button.getAttribute('aria-label'));
          if(!text||ignored.test(text)||label||button.getAttribute('role')==='radio'||button.closest('nav,header,[role="dialog"]'))return false;
          const blocks=[...button.querySelectorAll('p,div,span')].map(x=>norm(x.innerText)).filter(Boolean);
          return blocks.length>=2 || (blocks.length===1&&text.length>20);
        }).forEach(button=>{
          const raw=String(button.innerText||'').trim(); const text=norm(raw);
          const lines=raw.split(/\\n+/).map(norm).filter(Boolean);
          const key=JSON.stringify([lines[0]||text,text]);
          if(!found.has(key))found.set(key,{title:lines[0]||text,preview:lines.slice(1).join(' '),handle:{visible_text:text,title:lines[0]||text,preview:lines.slice(1).join(' ')}});
        });
        if(found.size===last)stable++;else stable=0;last=found.size;
        const before=container.scrollTop;container.scrollTop=Math.min(container.scrollHeight,container.scrollTop+Math.max(300,container.clientHeight*.8));
        container.dispatchEvent(new Event('scroll',{bubbles:true}));await new Promise(r=>setTimeout(r,350));
        if(container.scrollTop===before)stable++;
      }
      container.scrollTop=0;container.dispatchEvent(new Event('scroll',{bubbles:true}));return [...found.values()];
    }`);
    return rows;
  }
  async openJournalEntry(handle) { const text=String(handle?.visible_text||''); const title=String(handle?.title||''); const preview=String(handle?.preview||''); const ok=await this.run(`async () => {const n=s=>String(s||'').replace(/\\s+/g,' ').trim();const visible=e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0};const scrollables=[document.scrollingElement,...document.querySelectorAll('main,section,div')].filter((x,i,a)=>x&&a.indexOf(x)===i&&x.scrollHeight>x.clientHeight+20).sort((a,b)=>(b.scrollHeight-b.clientHeight)-(a.scrollHeight-a.clientHeight));const container=scrollables[0]||document.scrollingElement;for(let attempt=0;attempt<80;attempt++){const buttons=[...document.querySelectorAll('button')].filter(visible);const exact=buttons.find(x=>n(x.innerText)===${JSON.stringify(text)});const semantic=buttons.find(x=>n(x.innerText).startsWith(${JSON.stringify(title)})&&(!${JSON.stringify(preview)}||n(x.innerText).includes(${JSON.stringify(preview)})));const button=exact||semantic;if(button){button.scrollIntoView({block:'center'});button.click();return true;}const before=container.scrollTop;container.scrollTop=Math.min(container.scrollHeight,container.scrollTop+Math.max(250,container.clientHeight*.7));container.dispatchEvent(new Event('scroll',{bubbles:true}));await new Promise(r=>setTimeout(r,150));if(container.scrollTop===before)break;}return false;}`);if(!ok)return false;for(let i=0;i<20;i++){if(await this.run(`() => Boolean(document.querySelector('textarea[maxlength="500"]'))`))return true;await sleep(100);}await this.run(`() => {const back=document.querySelector('button[aria-label="Back"]');if(back)back.click();return Boolean(back);}`).catch(()=>false);await sleep(200);return false; }
  async readJournalEditor() { const data=await this.run(`() => {const textarea=document.querySelector('textarea[maxlength="500"]');if(!textarea)return null;const norm=s=>String(s||'').replace(/\\s+/g,' ').trim();const remove=[...document.querySelectorAll('button[aria-label^="Remove" i]')];const keywords=remove.map(button=>{const parent=button.parentElement;const parentText=norm(parent?.innerText);if(parentText)return parentText;return norm(button.getAttribute('aria-label')).replace(/^Remove(?: keyword)?\\s*/i,'');}).filter(Boolean);const remoteId=[...document.querySelectorAll('[data-id],[data-entry-id],[data-journal-id]')].map(x=>x.getAttribute('data-entry-id')||x.getAttribute('data-journal-id')||x.getAttribute('data-id')).find(Boolean)||'';return {keywords:[...new Set(keywords)],description:textarea.value||'',remote_id:String(remoteId)};}`);if(!data)throw new Error(UI_MAP_ERROR);return data; }
  async returnToJournalList(){const ok=await this.run(`() => {const b=document.querySelector('button[aria-label="Back"]');if(!b)return false;b.click();return true;}`);if(!ok)throw new Error(UI_MAP_ERROR);await sleep(300);}
  async scan(scope){await this.debug('scan:start',{scope});await this.selectJournalScope(scope);await this.waitForJournalList();await this.debugDom('scan:list-ready');const handles=await this.scanJournalIndex();await this.debug('scan:index-complete',{candidateCount:handles.length,handles});const entries=[];const skipped=[];for(const [index,handle] of handles.entries()){try{await this.debug('scan:opening-entry',{index,handle});const opened=await this.openJournalEntry(handle);if(!opened){skipped.push(handle.title);await this.debug('scan:entry-skipped',{index,reason:'editor did not open'});continue;}const value=await this.readJournalEditor();entries.push({...value,title:value.keywords[0]||handle.title,remote_handle:handle});await this.debug('scan:entry-read',{index,keywords:value.keywords,descriptionLength:value.description.length,remoteId:value.remote_id});await this.returnToJournalList();}catch(error){skipped.push(handle.title);await this.debug('scan:entry-error',{index,error:error.message});const inEditor=await this.run(`() => Boolean(document.querySelector('textarea[maxlength="500"]'))`).catch(()=>false);if(inEditor)await this.returnToJournalList().catch(()=>{});}}await this.debug('scan:complete',{entriesRead:entries.length,skipped});if(handles.length&&!entries.length)throw new Error(`JOURNAL LIST COULD NOT BE FULLY SCANNED (${handles.length} row candidates found; none opened as journal entries)`);return {scope,entries,skipped_candidates:skipped};}
  async openNewJournalEditor(){const ok=await this.run(`() => {const buttons=[...document.querySelectorAll('button')];const b=buttons.find(x=>/add|new|create/i.test(x.getAttribute('aria-label')||''))||buttons.find(x=>x.querySelector('svg')&&/plus/i.test(x.innerHTML));if(!b)return false;b.click();return true;}`);if(!ok)throw new Error(UI_MAP_ERROR);await sleep(300);}
  async replaceJournalKeywords(keywords){if(keywords.length>8||keywords.some(x=>x.length>50))throw new Error('Invalid journal keywords.');await this.run(`async () => {for(const b of document.querySelectorAll('button[aria-label^="Remove"]')){b.click();await new Promise(r=>setTimeout(r,30));}const input=document.querySelector('input[placeholder="Add another"]');if(!input)return false;for(const word of ${JSON.stringify(keywords)}){const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(input,word);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true}));await new Promise(r=>setTimeout(r,80));}return true;}`);}
  async replaceJournalDescription(description){const ok=await this.run(`() => {const t=document.querySelector('textarea[maxlength="500"]');if(!t)return false;Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(t,${JSON.stringify(description)});t.dispatchEvent(new Event('input',{bubbles:true}));t.dispatchEvent(new Event('change',{bubbles:true}));return true;}`);if(!ok)throw new Error(UI_MAP_ERROR);}
  async clickText(text){const ok=await this.run(`() => {const n=s=>String(s||'').replace(/\\s+/g,' ').trim();const b=[...document.querySelectorAll('button')].find(x=>n(x.textContent)===${JSON.stringify(text)});if(!b)return false;b.click();return true;}`);if(!ok)throw new Error(UI_MAP_ERROR);await sleep(450);}
  async saveJournalEntry(){await this.clickText('Save changes');}
  async deleteJournalEntry(){await this.clickText('Delete entry');await this.clickText('Delete');}
}
module.exports={KindroidJournalAdapter,UI_MAP_ERROR};
