'use strict';

const UI_MAP_ERROR = 'KINDROID JOURNAL UI MAP NEEDS UPDATE';
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

class KindroidJournalAdapter {
  constructor(window) { this.window = window; }
  async run(source) { if (!this.window || this.window.isDestroyed()) throw new Error('Journal window is unavailable.'); return this.window.webContents.executeJavaScript(`(${source})()`); }
  async openJournalPage(aiId) { const id=String(aiId||'').trim(); if(!/^[A-Za-z0-9_-]{6,128}$/.test(id))throw new Error('NO VALID DIRECTORY AI ID'); await this.window.loadURL(`https://kindroid.ai/v2/kin-settings/${encodeURIComponent(id)}/?tab=journal`); await sleep(1200); const url=this.window.webContents.getURL(); if(/login|signin|auth/i.test(url))throw new Error('LOGIN REQUIRED'); }
  async selectJournalScope(scope) { const wanted=scope==='global'?'Global':'Personal'; const ok=await this.run(`() => { const norm=s=>String(s||'').replace(/\\s+/g,' ').trim(); const button=[...document.querySelectorAll('button[role="radio"]')].find(x=>norm(x.textContent)===${JSON.stringify(wanted)}); if(!button)return false;if(button.getAttribute('aria-checked')!=='true')button.click();return true; }`); if(!ok)throw new Error(scope==='global'?'GLOBAL SCOPE COULD NOT BE SELECTED':UI_MAP_ERROR); await sleep(400); const selected=await this.run(`() => [...document.querySelectorAll('button[role="radio"]')].some(x=>String(x.textContent||'').trim()===${JSON.stringify(wanted)}&&x.getAttribute('aria-checked')==='true')`); if(!selected)throw new Error(UI_MAP_ERROR); }
  async waitForJournalList() { for(let i=0;i<30;i++){const ok=await this.run(`() => Boolean(document.querySelector('button[aria-label="Back"]') || document.querySelector('textarea[maxlength="500"]') || [...document.querySelectorAll('button')].some(b=>/add|new|create/i.test(b.getAttribute('aria-label')||'')) || document.querySelector('button svg'))`);if(ok)return;await sleep(200);}throw new Error('JOURNAL PAGE FAILED TO LOAD'); }
  async scanJournalIndex() {
    const rows=await this.run(`async () => { const norm=s=>String(s||'').replace(/\\s+/g,' ').trim(); const container=[...document.querySelectorAll('main,section,div')].filter(x=>x.scrollHeight>x.clientHeight+20).sort((a,b)=>b.clientHeight-a.clientHeight)[0]||document.scrollingElement; const found=new Map(); let stable=0,last=-1; while(stable<4){[...document.querySelectorAll('button')].filter(b=>{const t=norm(b.innerText);return t&&t!=='Global'&&t!=='Personal'&&!/save changes|delete entry/i.test(t)&&b.querySelector('div,p,span');}).forEach(b=>{const text=norm(b.innerText);if(!found.has(text))found.set(text,{title:text.split('\\n')[0]||text,preview:text,handle:{visible_text:text}});}); if(found.size===last)stable++;else stable=0;last=found.size;container.scrollTop+=Math.max(250,container.clientHeight*.75);await new Promise(r=>setTimeout(r,250)); } container.scrollTop=0; return [...found.values()]; }`);
    return rows;
  }
  async openJournalEntry(handle) { const text=String(handle?.visible_text||''); const ok=await this.run(`() => {const n=s=>String(s||'').replace(/\\s+/g,' ').trim();const b=[...document.querySelectorAll('button')].find(x=>n(x.innerText)===${JSON.stringify(text)});if(!b)return false;b.click();return true;}`);if(!ok)throw new Error(UI_MAP_ERROR);await sleep(350); }
  async readJournalEditor() { const data=await this.run(`() => {const textarea=document.querySelector('textarea[maxlength="500"],textarea');if(!textarea)return null;const remove=[...document.querySelectorAll('button[aria-label^="Remove"]')];const keywords=remove.map(b=>(b.getAttribute('aria-label')||'').replace(/^Remove\\s*/i,'').trim()).filter(Boolean);return {keywords,description:textarea.value||'',remote_id:location.hash.match(/[A-Za-z0-9_-]{6,}/)?.[0]||''};}`);if(!data)throw new Error(UI_MAP_ERROR);return data; }
  async returnToJournalList(){const ok=await this.run(`() => {const b=document.querySelector('button[aria-label="Back"]');if(!b)return false;b.click();return true;}`);if(!ok)throw new Error(UI_MAP_ERROR);await sleep(300);}
  async scan(scope){await this.selectJournalScope(scope);await this.waitForJournalList();const handles=await this.scanJournalIndex();const entries=[];for(const handle of handles){try{await this.openJournalEntry(handle);const value=await this.readJournalEditor();entries.push({...value,title:value.keywords[0]||handle.title,remote_handle:handle});await this.returnToJournalList();}catch(error){if(error.message===UI_MAP_ERROR)throw error;}}return {scope,entries};}
  async openNewJournalEditor(){const ok=await this.run(`() => {const buttons=[...document.querySelectorAll('button')];const b=buttons.find(x=>/add|new|create/i.test(x.getAttribute('aria-label')||''))||buttons.find(x=>x.querySelector('svg')&&/plus/i.test(x.innerHTML));if(!b)return false;b.click();return true;}`);if(!ok)throw new Error(UI_MAP_ERROR);await sleep(300);}
  async replaceJournalKeywords(keywords){if(keywords.length>8||keywords.some(x=>x.length>50))throw new Error('Invalid journal keywords.');await this.run(`async () => {for(const b of document.querySelectorAll('button[aria-label^="Remove"]')){b.click();await new Promise(r=>setTimeout(r,30));}const input=document.querySelector('input[placeholder="Add another"]');if(!input)return false;for(const word of ${JSON.stringify(keywords)}){const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(input,word);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true}));await new Promise(r=>setTimeout(r,80));}return true;}`);}
  async replaceJournalDescription(description){const ok=await this.run(`() => {const t=document.querySelector('textarea[maxlength="500"]');if(!t)return false;Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(t,${JSON.stringify(description)});t.dispatchEvent(new Event('input',{bubbles:true}));t.dispatchEvent(new Event('change',{bubbles:true}));return true;}`);if(!ok)throw new Error(UI_MAP_ERROR);}
  async clickText(text){const ok=await this.run(`() => {const n=s=>String(s||'').replace(/\\s+/g,' ').trim();const b=[...document.querySelectorAll('button')].find(x=>n(x.textContent)===${JSON.stringify(text)});if(!b)return false;b.click();return true;}`);if(!ok)throw new Error(UI_MAP_ERROR);await sleep(450);}
  async saveJournalEntry(){await this.clickText('Save changes');}
  async deleteJournalEntry(){await this.clickText('Delete entry');await this.clickText('Delete');}
}
module.exports={KindroidJournalAdapter,UI_MAP_ERROR};
